#
# This file is part of Edgehog.
#
# Copyright 2025 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

name: End to end test

on:
  # Run when pushing to stable branches
  push:
    paths:
      - "backend/**"
      - "tools/e2e_test/**"
      - ".tool-versions"
      - ".github/workflows/e2e-test.yaml"
    branches:
      - "main"
      - "release-*"
  # Run on pull requests matching apps
  pull_request:
    paths:
      - "backend/**"
      - "tools/e2e_test/**"
      - ".tool-versions"
      - ".github/workflows/e2e-test.yaml"

defaults:
  run:
    shell: bash
    working-directory: tools/e2e_test
env:
  EDGEHOG_TEST_TENANT: "test"
  EDGEHOG_TEST_HOSTNAME: "api.edgehog.localhost"
  EDGEHOG_TEST_BEARER: "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJlX3RnYSI6IioiLCJpYXQiOjE3Mzg5NDgzODh9.TTiXYs1LucAnS_6RGp7pWg-S30NSt7eqL7lU8BzT5BWlHctk7NYZwC6lftA6WeEb1HKEJfPoUqWeOeZ6oYA0AA"

jobs:
  e2e-test:
    name: End to end
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          show-progress: false
      - name: Install gleam and BEAM
        uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "1.13.0"
          rebar3-version: "3"
      - uses: mozilla-actions/sccache-action@v0.0.9
      - name: Setup `just`
        uses: extractions/setup-just@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install astartectl
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: astarte-platform/astartectl
      - name: Provision a tenant
        run: just provision-tenant
      - name: Run e2e test suite
        run: |
          gleam run
